[SERVICE]
    log_level    info
    flush        5
    daemon       off

[INPUT]
    name        systemd
    tag         journal.*
    read_from_tail on
    strip_underscores on
    lowercase on

[FILTER]
    name        wasm
    match       journal.*
    wasm_path   ./target/wasm32-unknown-unknown/release/logcheck_fluent_bit_filter.wasm
    function_name logcheck_filter_json
    accessible_paths .

[OUTPUT]
    name        stdout
    match       journal.*
    format      json_lines