//! Rule file writer for saving generated patterns to logcheck directories

use std::fs::{self, OpenOptions};
use std::io::Write;
use std::path::{Path, PathBuf};

use anyhow::{Context, Result};

/// Categories for logcheck rules
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum RuleCategory {
    /// Security violations to ignore (ignore.d.*/violations.ignore.d)
    Violations,
    /// Server-specific ignore rules
    Server,
    /// Workstation-specific ignore rules
    Workstation,
    /// Local custom rules
    Local,
}

impl RuleCategory {
    /// Get display name for UI
    pub fn display_name(&self) -> &'static str {
        match self {
            RuleCategory::Violations => "Violations",
            RuleCategory::Server => "Server",
            RuleCategory::Workstation => "Workstation",
            RuleCategory::Local => "Local",
        }
    }

    /// Get default subdirectory name within logcheck root
    pub fn subdirectory(&self) -> &'static str {
        match self {
            RuleCategory::Violations => "violations.ignore.d",
            RuleCategory::Server => "ignore.d.server",
            RuleCategory::Workstation => "ignore.d.workstation",
            RuleCategory::Local => "ignore.d.local",
        }
    }

    /// All available categories for iteration
    pub fn all() -> &'static [RuleCategory] {
        &[
            RuleCategory::Violations,
            RuleCategory::Server,
            RuleCategory::Workstation,
            RuleCategory::Local,
        ]
    }
}

/// Configuration for where to save rules
#[derive(Debug, Clone)]
pub struct RuleWriterConfig {
    /// Base directory for logcheck rules (e.g., /etc/logcheck or ~/.logcheck)
    pub base_dir: PathBuf,
    /// Default filename to append rules to
    pub filename: String,
}

impl Default for RuleWriterConfig {
    fn default() -> Self {
        Self {
            base_dir: PathBuf::from("/etc/logcheck"),
            filename: "local-generated".to_string(),
        }
    }
}

impl RuleWriterConfig {
    /// Create config with custom base directory
    pub fn with_base_dir<P: AsRef<Path>>(path: P) -> Self {
        Self {
            base_dir: path.as_ref().to_path_buf(),
            ..Default::default()
        }
    }

    /// Get full path for a rule file in given category
    pub fn get_path(&self, category: RuleCategory) -> PathBuf {
        self.base_dir
            .join(category.subdirectory())
            .join(&self.filename)
    }

    /// Check if base directory exists
    pub fn validate(&self) -> Result<()> {
        if !self.base_dir.exists() {
            anyhow::bail!(
                "Logcheck base directory does not exist: {}",
                self.base_dir.display()
            );
        }
        Ok(())
    }
}

/// Writer for saving rules to logcheck files
pub struct RuleWriter {
    config: RuleWriterConfig,
}

impl RuleWriter {
    /// Create new rule writer with given configuration
    pub fn new(config: RuleWriterConfig) -> Self {
        Self { config }
    }

    /// Create rule writer with default configuration
    pub fn with_default_config() -> Self {
        Self::new(RuleWriterConfig::default())
    }

    /// Save a rule pattern to the appropriate file
    ///
    /// # Arguments
    /// * `category` - Target rule category
    /// * `pattern` - Regex pattern in POSIX format (will be validated)
    /// * `match_count` - Number of log entries this pattern matches
    ///
    /// # Returns
    /// Path to the file where rule was saved
    pub fn save_rule(
        &self,
        category: RuleCategory,
        pattern: &str,
        match_count: usize,
    ) -> Result<PathBuf> {
        // Validate pattern is not empty
        if pattern.trim().is_empty() {
            anyhow::bail!("Pattern cannot be empty");
        }

        // Get target file path
        let target_path = self.config.get_path(category);

        // Ensure parent directory exists
        if let Some(parent) = target_path.parent() {
            fs::create_dir_all(parent)
                .with_context(|| format!("Failed to create directory {}", parent.display()))?;
        }

        // Format rule entry with metadata
        let timestamp = chrono::Local::now().format("%Y-%m-%d %H:%M:%S");
        let rule_entry = format!(
            "# Generated by logcheck-filter on {}\n# Matches {} log entries\n{}\n",
            timestamp, match_count, pattern
        );

        // Append to file (create if doesn't exist)
        let mut file = OpenOptions::new()
            .create(true)
            .append(true)
            .open(&target_path)
            .with_context(|| format!("Failed to open {}", target_path.display()))?;

        file.write_all(rule_entry.as_bytes())
            .with_context(|| format!("Failed to write to {}", target_path.display()))?;

        Ok(target_path)
    }

    /// Get the configuration being used
    pub fn config(&self) -> &RuleWriterConfig {
        &self.config
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::fs;
    use tempfile::TempDir;

    #[test]
    fn test_rule_category_display() {
        assert_eq!(RuleCategory::Violations.display_name(), "Violations");
        assert_eq!(RuleCategory::Server.display_name(), "Server");
        assert_eq!(RuleCategory::Workstation.display_name(), "Workstation");
        assert_eq!(RuleCategory::Local.display_name(), "Local");
    }

    #[test]
    fn test_rule_category_subdirectory() {
        assert_eq!(
            RuleCategory::Violations.subdirectory(),
            "violations.ignore.d"
        );
        assert_eq!(RuleCategory::Server.subdirectory(), "ignore.d.server");
        assert_eq!(
            RuleCategory::Workstation.subdirectory(),
            "ignore.d.workstation"
        );
        assert_eq!(RuleCategory::Local.subdirectory(), "ignore.d.local");
    }

    #[test]
    fn test_config_path_generation() {
        let config = RuleWriterConfig {
            base_dir: PathBuf::from("/etc/logcheck"),
            filename: "test-rules".to_string(),
        };

        let path = config.get_path(RuleCategory::Server);
        assert_eq!(
            path,
            PathBuf::from("/etc/logcheck/ignore.d.server/test-rules")
        );
    }

    #[test]
    fn test_save_rule() -> Result<()> {
        // Create temporary directory
        let temp_dir = TempDir::new()?;
        let base_dir = temp_dir.path().to_path_buf();

        // Create subdirectories
        fs::create_dir_all(base_dir.join("ignore.d.server"))?;

        // Configure writer
        let config = RuleWriterConfig {
            base_dir: base_dir.clone(),
            filename: "test-generated".to_string(),
        };
        let writer = RuleWriter::new(config);

        // Save a rule
        let pattern = r"^pam_unix\(sudo:session\): session [[:alpha:]]+ for user";
        let saved_path = writer.save_rule(RuleCategory::Server, pattern, 52)?;

        // Verify file was created
        assert!(saved_path.exists());
        assert_eq!(saved_path, base_dir.join("ignore.d.server/test-generated"));

        // Verify content
        let content = fs::read_to_string(&saved_path)?;
        assert!(content.contains("# Generated by logcheck-filter on"));
        assert!(content.contains("# Matches 52 log entries"));
        assert!(content.contains(pattern));

        Ok(())
    }

    #[test]
    fn test_save_multiple_rules() -> Result<()> {
        let temp_dir = TempDir::new()?;
        let base_dir = temp_dir.path().to_path_buf();
        fs::create_dir_all(base_dir.join("ignore.d.local"))?;

        let config = RuleWriterConfig::with_base_dir(&base_dir);
        let writer = RuleWriter::new(config);

        // Save multiple rules
        writer.save_rule(RuleCategory::Local, "^pattern1$", 10)?;
        writer.save_rule(RuleCategory::Local, "^pattern2$", 20)?;

        // Verify both rules in file
        let path = base_dir.join("ignore.d.local/local-generated");
        let content = fs::read_to_string(&path)?;

        assert!(content.contains("^pattern1$"));
        assert!(content.contains("^pattern2$"));
        assert!(content.contains("# Matches 10 log entries"));
        assert!(content.contains("# Matches 20 log entries"));

        Ok(())
    }

    #[test]
    fn test_empty_pattern_rejected() {
        let temp_dir = TempDir::new().unwrap();
        let config = RuleWriterConfig::with_base_dir(temp_dir.path());
        let writer = RuleWriter::new(config);

        let result = writer.save_rule(RuleCategory::Local, "", 5);
        assert!(result.is_err());
        assert!(result
            .unwrap_err()
            .to_string()
            .contains("Pattern cannot be empty"));
    }

    #[test]
    fn test_directory_creation() -> Result<()> {
        let temp_dir = TempDir::new()?;
        let base_dir = temp_dir.path().to_path_buf();

        // Don't pre-create directories
        let config = RuleWriterConfig::with_base_dir(&base_dir);
        let writer = RuleWriter::new(config);

        // Should auto-create directory
        writer.save_rule(RuleCategory::Violations, "^test$", 1)?;

        let dir = base_dir.join("violations.ignore.d");
        assert!(dir.exists());
        assert!(dir.is_dir());

        Ok(())
    }
}
